# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e41caf3fba4313e2b0c431f26898e39a6d849566cb5ab0c9340941245fb02f907be101d0d79c57efe1877f963d1b4212c729160b56175cdcb6e865b0492689e

test:
  secret_key_base: 89786d2c005cdd06557006a91c5069f0e2efbb3d106412b5fbceac406eade86e79a9a9a24635ea5326c9eda846ce7d6cd869921a84955951234ae8b5d28616ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
